server:
  port: 1115
spring:
  profiles:
    active: prod
  application:
    name: product-center
  cloud:
    config:
      label: master
      profile: prod
      uri: http://localhost:1119
      name: config-prod
      discovery:
        serviceId: config-center
        enabled: true
#Eureka
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://registry-center:1111/eureka/

xtt:
  name: product-center-prod-xtt
