server:
  port: 1118

#eureka
eureka:
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://registry-center:1111/eureka/

spring:
  application:
    name: gateway-center

#路由
zuul:
  routes:
    #后台路由
    manager:
      path: /manager/**
      serviceId: manager
    #商品中心
    product-center:
      path: /product-center/**
      serviceId: product-center
    #配置中心
    config-center:
      path: /config-center/**
      serviceId: config-center